language: python
python:
    - "3.5"
before_install:
    - pip install pytest pytest-cov
    - pip install coveralls
    - pip install ply
    - pip install scipy
script:
    - py.test
after_success:
    - coveralls
