
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = '07B833D82A5F316C55D6CFE4C45D52FE'
    
_lr_action_items = {'LIMIT':([7,8,9,10,27,28,31,35,36,37,38,],[17,-17,-13,-16,-17,-15,34,40,-19,-18,-14,]),'LPAREN':([8,],[18,]),'COMMA':([8,9,10,12,13,27,28,30,38,],[-17,19,-16,22,-12,-17,-15,-11,19,]),'ORDER':([7,8,9,10,27,28,38,],[16,-17,-13,-16,-17,-15,-14,]),'RPAREN':([18,],[26,]),'ASC':([31,],[37,]),'DESC':([31,],[36,]),'BY':([16,],[24,]),'AS':([26,],[32,]),'FROM':([3,7,8,9,10,27,28,38,],[6,15,-17,-13,-16,-17,-15,-14,]),'$end':([1,7,8,9,10,14,23,25,27,28,31,33,35,36,37,38,39,41,],[0,-4,-17,-13,-16,-2,-3,-5,-17,-15,-6,-1,-7,-19,-18,-14,-8,-9,]),'AT':([4,21,],[11,-10,]),'LBRACK':([2,11,],[5,5,]),'ID':([3,6,15,19,24,29,32,],[8,14,23,27,31,33,27,]),'INSERT':([0,],[2,]),'SELECT':([0,],[3,]),'INTO':([20,21,],[29,-10,]),'RBRACK':([12,13,30,],[21,-12,-11,]),'NUMBER':([5,17,22,34,40,],[13,25,30,39,41,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bracketed_number_list':([2,11,],[4,20,]),'command':([0,],[1,]),'selector':([3,],[7,]),'number_list':([5,],[12,]),'field_list':([3,32,],[9,38,]),'field_name':([3,19,32,],[10,28,10,]),'order_direction':([31,],[35,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> INSERT bracketed_number_list AT bracketed_number_list INTO ID','command',6,'p_insert_command','parser.py',8),
  ('command -> SELECT FROM ID','command',3,'p_select_from','parser.py',13),
  ('command -> SELECT selector FROM ID','command',4,'p_select_from','parser.py',14),
  ('command -> SELECT selector','command',2,'p_select_multi','parser.py',25),
  ('command -> SELECT selector LIMIT NUMBER','command',4,'p_select_multi','parser.py',26),
  ('command -> SELECT selector ORDER BY ID','command',5,'p_select_multi','parser.py',27),
  ('command -> SELECT selector ORDER BY ID order_direction','command',6,'p_select_multi','parser.py',28),
  ('command -> SELECT selector ORDER BY ID LIMIT NUMBER','command',7,'p_select_multi','parser.py',29),
  ('command -> SELECT selector ORDER BY ID order_direction LIMIT NUMBER','command',8,'p_select_multi','parser.py',30),
  ('bracketed_number_list -> LBRACK number_list RBRACK','bracketed_number_list',3,'p_bracketed_number_list','parser.py',50),
  ('number_list -> number_list COMMA NUMBER','number_list',3,'p_number_list','parser.py',55),
  ('number_list -> NUMBER','number_list',1,'p_number_list','parser.py',56),
  ('selector -> field_list','selector',1,'p_selector','parser.py',66),
  ('selector -> ID LPAREN RPAREN AS field_list','selector',5,'p_selector','parser.py',67),
  ('field_list -> field_list COMMA field_name','field_list',3,'p_field_list','parser.py',75),
  ('field_list -> field_name','field_list',1,'p_field_list','parser.py',76),
  ('field_name -> ID','field_name',1,'p_field_name','parser.py',86),
  ('order_direction -> ASC','order_direction',1,'p_order_direction','parser.py',91),
  ('order_direction -> DESC','order_direction',1,'p_order_direction','parser.py',92),
]
