
# parsetab.py
# This file is automatically generated. Do not edit.
_tabversion = '3.8'

_lr_method = 'LALR'

_lr_signature = 'A2B477C12B901A11BD4D0BB509E25F33'
    
_lr_action_items = {'ORDER':([7,8,9,10,26,27,38,],[15,-13,-16,-17,-15,-17,-14,]),'AT':([4,22,],[11,-10,]),'BY':([15,],[23,]),'FROM':([3,7,8,9,10,26,27,38,],[6,16,-13,-16,-17,-15,-17,-14,]),'LBRACK':([2,11,],[5,5,]),'LIMIT':([7,8,9,10,26,27,31,34,35,36,38,],[17,-13,-16,-17,-15,-17,37,-19,-18,39,-14,]),'$end':([1,7,8,9,10,14,24,25,26,27,31,33,34,35,36,38,40,41,],[0,-4,-13,-16,-17,-2,-3,-5,-15,-17,-6,-1,-19,-18,-7,-14,-8,-9,]),'COMMA':([8,9,10,12,13,26,27,30,38,],[18,-16,-17,-12,21,-15,-17,-11,18,]),'RPAREN':([19,],[28,]),'ASC':([31,],[35,]),'RBRACK':([12,13,30,],[-12,22,-11,]),'DESC':([31,],[34,]),'AS':([28,],[32,]),'INSERT':([0,],[2,]),'SELECT':([0,],[3,]),'NUMBER':([5,17,21,37,39,],[12,25,30,40,41,]),'INTO':([20,22,],[29,-10,]),'LPAREN':([10,],[19,]),'ID':([3,6,16,18,23,29,32,],[10,14,24,27,31,33,27,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'bracketed_number_list':([2,11,],[4,20,]),'field_name':([3,18,32,],[9,26,9,]),'number_list':([5,],[13,]),'selector':([3,],[7,]),'field_list':([3,32,],[8,38,]),'order_direction':([31,],[36,]),'command':([0,],[1,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> command","S'",1,None,None,None),
  ('command -> INSERT bracketed_number_list AT bracketed_number_list INTO ID','command',6,'p_insert_command','parser.py',8),
  ('command -> SELECT FROM ID','command',3,'p_select_from','parser.py',13),
  ('command -> SELECT selector FROM ID','command',4,'p_select_from','parser.py',14),
  ('command -> SELECT selector','command',2,'p_select_multi','parser.py',25),
  ('command -> SELECT selector LIMIT NUMBER','command',4,'p_select_multi','parser.py',26),
  ('command -> SELECT selector ORDER BY ID','command',5,'p_select_multi','parser.py',27),
  ('command -> SELECT selector ORDER BY ID order_direction','command',6,'p_select_multi','parser.py',28),
  ('command -> SELECT selector ORDER BY ID LIMIT NUMBER','command',7,'p_select_multi','parser.py',29),
  ('command -> SELECT selector ORDER BY ID order_direction LIMIT NUMBER','command',8,'p_select_multi','parser.py',30),
  ('bracketed_number_list -> LBRACK number_list RBRACK','bracketed_number_list',3,'p_bracketed_number_list','parser.py',50),
  ('number_list -> number_list COMMA NUMBER','number_list',3,'p_number_list','parser.py',55),
  ('number_list -> NUMBER','number_list',1,'p_number_list','parser.py',56),
  ('selector -> field_list','selector',1,'p_selector','parser.py',66),
  ('selector -> ID LPAREN RPAREN AS field_list','selector',5,'p_selector','parser.py',67),
  ('field_list -> field_list COMMA field_name','field_list',3,'p_field_list','parser.py',75),
  ('field_list -> field_name','field_list',1,'p_field_list','parser.py',76),
  ('field_name -> ID','field_name',1,'p_field_name','parser.py',86),
  ('order_direction -> ASC','order_direction',1,'p_order_direction','parser.py',91),
  ('order_direction -> DESC','order_direction',1,'p_order_direction','parser.py',92),
]
